lesson-10
DariaRomanowska/if-html pull request #10
Opened 2022-08-10 22:44 UTC by DariaRomanowska

2022-08-14 19:02 UTC, 5tronciy requested changes
The block "Homes guests loves" looks not bad. But the issue with the first section brokes the layout on low-width screens. Look throw my comments also.

2022-08-14 19:02 UTC, 5tronciy commented on styles/styles.css
> +  grid-template-rows: repeat(4, auto);
Implicit adding of margin-bottom value. It is not clear to understand.

2022-08-14 19:02 UTC, 5tronciy commented on styles/styles.css
> +  }
A rather extreme solution. People don't expect disabling pseudo-elements by default.

2022-08-14 19:02 UTC, 5tronciy commented on index.html
> +        <div class="gallery">
I think a consequence of simplifying this block is the subsequent technique of hiding elements by `div.gallery p:nth-last-of-type(1...4)`. It is bad that the styles depend on the content there.

2022-08-14 19:02 UTC, 5tronciy commented on styles/styles.css
> +  div.gallery img:nth-last-of-type(1){
You used class `gallery` before. Why clarify that it is div here?

2022-08-22 20:58 UTC, DariaRomanowska commented on styles/styles.css
> +  }
They are not in the design, but in the mobile version, the hover will still not work. What can I do in this case?

2022-08-22 20:59 UTC, DariaRomanowska commented on styles/styles.css
> +  grid-template-rows: repeat(4, auto);
I don't understand what do you mean

2022-08-22 21:09 UTC, DariaRomanowska commented on index.html
> +        <div class="gallery">
In styles, I used this method. What does styles depend on content mean? Aren't styles writtening to the content?

2022-08-23 19:50 UTC, 5tronciy commented on styles/styles.css
> +  grid-template-rows: repeat(4, auto);
There are 3 rows with content. And as you add the 4th row without content in the template there is an additional gap at the bottom. And it works as margin-bottom but you have written it in a non-obvious way.
![Снимок экрана 2022-08-23 в 21 48 49](https://user-images.githubusercontent.com/62604867/186252851-70b8e421-2d4a-46ff-a069-578301492e3e.png)

2022-08-23 19:57 UTC, 5tronciy commented on styles/styles.css
> +  }
What about using concrete classes instead of `*` (every element in the document)?

2022-08-23 20:09 UTC, 5tronciy commented on index.html
> +        <div class="gallery">
Content is changeable like the design. In this case, your style works for a max of 4 tiles. 
And you wrote 6 selectors just for hiding 2 tiles. What if we decide to increase the number of tiles?
It is better to find ways of writing common styles independent of content.

2022-08-30 16:27 UTC, 5tronciy approved these changes
Looks good.
10th lesson's requirements are fully assigned.

2022-08-30 16:29 UTC, merged