Lesson 12
DariaRomanowska/if-html pull request #12
Opened 2022-08-21 18:23 UTC by DariaRomanowska

2022-08-23 21:02 UTC, 5tronciy requested changes
Looks good. Just pagination on mobile view missed.

![Снимок экрана 2022-08-23 в 22 34 08](https://user-images.githubusercontent.com/62604867/186265006-2b9193de-1d10-46b0-bd0a-dcf2d676134f.png)

2022-08-23 21:02 UTC, 5tronciy commented on styles/styles.css
> +  margin-top: 104px;
Non-obvious place of margin declaration.  `.reviews--title{margin-bottom: 104px;}` looks clearly.

2022-08-23 21:02 UTC, 5tronciy commented on index.html
> +        <div class="reviews--top _bali">
Are you going to add a unique class for every possible hotel? Btw, do you use it anyway?

2022-08-23 21:02 UTC, 5tronciy commented on index.html
> +              advice.
Check font styles here. It differs from the design.

2022-08-23 22:20 UTC, DariaRomanowska commented on index.html
> +        <div class="reviews--top _bali">
Yes, I used them to hiden for mobile version

2022-08-23 22:30 UTC, DariaRomanowska commented on index.html
> +              advice.
<img width="888" alt="Screenshot_2" src="https://user-images.githubusercontent.com/108368868/186277179-a1224ff0-8c15-4b79-8f46-c3efce3b4d32.png">

it is the same as in design

2022-08-30 17:08 UTC, 5tronciy approved these changes
All the issues are fixed. Good work!

2022-08-30 17:16 UTC, merged