Added image, list, table, form and button to index.html. Added <meta>
DariaRomanowska/if-html pull request #2
Opened 2022-07-09 18:21 UTC by DariaRomanowska

2022-07-12 08:47 UTC, 5tronciy requested changes
In general good. But you have ignored my remarks for the last PR.
Make commit with changes before merge this PR.

2022-07-12 08:47 UTC, 5tronciy commented on index.html
> +      <a href="./about">Об авторе</a>
Does it work in your browser?

2022-07-12 08:47 UTC, 5tronciy commented on index.html
> +        <p>
`<p></p>` is for the text paragraph.
Block should be wrapped into `<div></div>`

2022-07-12 08:47 UTC, 5tronciy commented on index.html
> +            min="0"
0 doesn't match the range 1-10.

2022-07-12 09:13 UTC, DariaRomanowska commented on index.html
> +      <a href="./about">Об авторе</a>
Yes, it works, but now I changed it to the full way

2022-07-14 21:51 UTC, 5tronciy approved these changes
Looks good.

2022-07-14 21:52 UTC, merged